### ISSUE TITLE
【文章自荐】关于 Golang 多平台打包发布这件事..

### ISSUE THREAD

**Issue by LeslieLeung** [eryajf/learning-weekly#12]
- 文章标题：关于 Golang 多平台打包发布这件事..
- 文章链接： https://github.com/LeslieLeung/go-multiplatform-docker/blob/main/doc/README.md
- 文章摘要： 一个演示如何使用 GitHub Actions 将一个 Golang 项目打包成多平台的二进制文件并发布到 GitHub Releases 和 DockerHub 的例子。

**Comment by eryajf** [comment]
哈哈，这篇文章已经被我预收录了😂

![image_20220725_234512](https://cdn.staticaly.com/gh/eryajf/tu/main/img/image_20220725_234512.png)

这不巧了吗不是

**Comment by LeslieLeung** [comment]
感谢推荐！
