### ISSUE TITLE
【文章推荐/文章自荐】Raft算法深度剖析，让你远离分布式恐惧

### ISSUE THREAD

**Issue by magiWei** [eryajf/learning-weekly#18]
https://mp.weixin.qq.com/s?__biz=MzIwNDAyOTI2Nw==&mid=2247484086&idx=1&sn=93fd914f3f77d799113d2a368bfa3f01&chksm=96c72e8aa1b0a79c60feade157fcc711b8535638b2f4e1793c0ef9f3f0685a4cff538ec19a65&token=2074428159&lang=zh_CN#rd

**Comment by eryajf** [comment]
收
